### ISSUE TITLE
Rpc hardcoded retry

### ISSUE THREAD

**Issue by maximilianom** [OpenTSDB/asynchbase#105]
Hi, I'm trying to make an application to use this library and fail fast when it can't connect to the server. The hardcoded property in the HBaseClient line 1774 ` return rpc.attempt > 10;  // XXX Don't hardcode.` makes it too slow for the client to call the errCallback.

Is there any specific reason for this? Could it be exposed as a property or passed through the constructor of the class?

Thanks

**Comment by tsuna** [comment]
If you want the RPC to "fail fast", then the recommended way is to call `setFailfast(true)` on your RPC.
