### ISSUE TITLE
Add support for backward scanning

### ISSUE THREAD

**Issue by caprius** [OpenTSDB/asynchbase#111]
Hello, I was wondering if there's a plan to add support for backward scanning for Hbase 0.98 / CDH5?  Thanks!

**Comment by tsuna** [comment]
Yeah that would be nice.  Can you send a pull request?

**Comment by caprius** [comment]
A quick update: we (https://github.com/jnfang) have been working on this pull request and will send it once it's done.

**Comment by HeartSaVioR** [comment]
@caprius @jnfang 
Hello, I need this feature in our project.
I skimmed https://github.com/jnfang/asynchbase and found @jnfang already did some works, but seems like it's stopped.
So I'd like to ask you when it will be done (I mean pull request for OpenTSDB/asyncbase is available).

If it will take some times (say, in 1 month), or you decided to not going forward, I'd like to take over this.
(Are you OK that I could cherry-pick or copy your commits into my branch?)

**Comment by HeartSaVioR** [comment]
Can be closed finally. :)

**Comment by IDerr** [comment]
You can close this @manolama https://github.com/OpenTSDB/asynchbase/commit/f6a8ccb7e55ed9bc0aad265345da4c679e750055

**Comment by manolama** [comment]
Thanks @IDerr @HeartSaVioR
