### ISSUE TITLE
Javadoc for HBaseClient is inaccurate

### ISSUE THREAD

**Issue by hsun-cnnxty** [OpenTSDB/asynchbase#123]
The javadoc for two of the constructors has zookeeper quorum property defined as  "asynchbase.zk.quorum" instead of "hbase.zookeeper.quorum".

    /**
     * Constructor accepting a configuration object with at least the 
     * "asynchbase.zk.quorum" specified in the format {@code "host1,host2,host3"}.
     */    
     public HBaseClient(final Config config)
   
    /**
     * Constructor accepting a configuration object with at least the 
     * "asynchbase.zk.quorum" specified in the format {@code "host1,host2,host3"}
     * and an executor thread pool. ..
     */
     public HBaseClient(final Config config, final Executor executor)

**Comment by manolama** [comment]
Oops, sorry, that snuck in from downstream.

**Comment by manolama** [comment]
Merged in 6956dc2675d4e392b8773f362ec2e9a20d0a6fa9
