### ISSUE TITLE
Tag 1.7.2?

### ISSUE THREAD

**Issue by jongwook** [OpenTSDB/asynchbase#141]
Hi, we depend on some fixes that have been added after `1.7.1`, but maintaining a separate repo for the SNAPSHOT jar is a small burden, and it doesn't seem that there is a public snapshot repository for asynchbase.

Is there any plan for tagging `1.7.2` soon?

**Comment by manolama** [comment]
Finally cut it today, thanks! c68b906cdc727f12cc601a95019d57b2f4bb9ce4
