### ISSUE TITLE
AsyncHBase compatibility with HBase 1.3.1

### ISSUE THREAD

**Issue by karanmehta93** [OpenTSDB/asynchbase#164]
[https://issues.apache.org/jira/browse/HBASE-18000](HBASE-18000) was one of the reasons for this. 
This was fixed in version 1.3.2. Manual back-port needed for 1.3.1, if required. 
[https://issues.apache.org/jira/browse/HBASE-18042](HBASE-18042) is the problem seen after the first one was fixed. This issue is to patch AsyncHBase to update the client with the new upstream changes in HBase.
Following changes are required. 
1. Client Protos in next branch are outdated. New optional fields have been added
2. The way in which client sends RPC's have also to be updated based on the information from these fields.

**Comment by karanmehta93** [comment]
This patch will not handle partial results or heartbeat messages, the features that were included from HBase - 1.1, since this will lead to changing the way how AsyncHBase returns outputs to the user. Currently it is as Deferred<ArrayList<ArrayList<KeyValue>> with no appropriate way to define if the results are partial or complete.

**Comment by manolama** [comment]
> This patch will not handle partial results or heartbeat messages, the features that were included from HBase - 1.1, since this will lead to changing the way how AsyncHBase returns outputs to the user. Currently it is as Deferred<ArrayList<ArrayList> with no appropriate way to define if the results are partial or complete.

We could probably add separate API's for the new types. I dislike them being ``ArrayList`` anyway.

**Comment by manolama** [comment]
Merged @karanmehta93's patch in 80c6b86084a1bf75078e1c4419b25193117c116e.

**Comment by aarbor989** [comment]
This patch looks incomplete.  Same changes also need to be made on lines 1518-1520
