### ISSUE TITLE
GetRequest lost `family()`

### ISSUE THREAD

**Issue by djova** [OpenTSDB/asynchbase#174]
In https://github.com/OpenTSDB/asynchbase/commit/928be286d72f3a8cf35b63190ae782da28d5da01#diff-be93c103bf1c94e6ef7b69706972da13L458 the public getter `GetRequest#family()` was removed. The result is that calling `family()` on a `GetRequest` instance invokes `BatchableRpc#family()` which will always return `null`. 

`GetRequest` should probably use `BatchableRpc#family` to store the family instead of having its own variable which hides the base class' variable.

**Comment by manolama** [comment]
Merged @jasonculverhouse's fix in 869fcee2bcb529a1d352b28974a230e1cd5b190a.
