### ISSUE TITLE
IN version2.3.0

### ISSUE THREAD

**Issue by bigpws** [OpenTSDB/asynchbase#194]
Unexpected exception from downstream on [id: 0xbcf1d7a4, /127.0.0.1:33132 => /127.0.0.1:41188]	java.lang.AssertionError: Must not be used. 	at org.hbase.async.HBaseException.make(HBaseException.java:62) ~[asynchbase-1.7.2.jar:na] 	at org.hbase.async.RegionClient$1MultiActionCallback.handleException(RegionClient.java:903) ~[asynchbase-1.7.2.jar:na] 	at org.hbase.async.RegionClient$1MultiActionCallback.call(RegionClient.java:867) ~[asynchbase-1.7.2.jar:na] 	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na] 	at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na] 	at com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[async-1.4.0.jar:na] 	at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712) ~[asynchbase-1.7.2.jar:na] 	at org.hbase.async.RegionClient.decode(RegionClient.java:1509) ~[asynchbase-1.7.2.jar:na] 	at org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.7.2.jar:na] 	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na] 	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na] 	at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1223) ~[asynchbase-1.7.2.jar:na] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na] 	at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3121) [asynchbase-1.7.2.jar:na] 	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na] 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161] 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
--

Wed May 16 09:31:42 GMT+800 2018 | ERROR | AsyncHBase I/O Worker #3 | async.RegionClient
Uncaught error during de-serialization of MultiAction(batch=[PutRequest(table="tsdb", key=[0, 0, 7, 90, -5, -126, -112, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 3, 0, 0, 3], family="t", qualifiers=["\xF7DZ\x0B"], values=["<\x03\x12o"], timestamp=9223372036854775807, lockid=-1, durable=true, bufferable=true, attempt=2, region=RegionInfo(table="tsdb", region_name="tsdb,,1526433350905.97227d7f1e5948a4de6971f6ce628d1b.", stop_key="")), PutRequest(table="tsdb", key=[0, 0, 8, 90, -5, -126, -112, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 3, 0, 0, 3], family="t", qualifiers=["\xF7DZ\x0B"], values=[[-69, -125, 18, 111]], timestamp=9223372036854775807, lockid=-1, durable=true, bufferable=true, attempt=1, region=RegionInfo(table="tsdb", region_name="tsdb,,1526433350905.97227d7f1e5948a4de6971f6ce628d1b.", stop_key="")), PutRequest(table="tsdb", key=[0, 0, 9, 90, -5, -126, -112, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 3, 0, 0, 4], family="t", qualifiers=["\xF7DZ\x00"], values=["\x01"], timestamp=9223372036854775807, lockid=-1, durable=true, bufferable=true, attempt=1, region=RegionInfo(table="tsdb", region_name="tsdb,,1526433350905.97227d7f1e5948a4de6971f6ce628d1b.", stop_key="")), ... 67 RPCs not shown ..., PutRequest(table="tsdb", key=[0, 0, 71, 90, -5, -126, -112, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 3, 0, 0, 9], family="t", qualifiers=["\xF7DZ\x00"], values=["\x00"], timestamp=9223372036854775807, lockid=-1, durable=true, bufferable=true, attempt=1, region=RegionInfo(table="tsdb", region_name="tsdb,,1526433350905.97227d7f1e5948a4de6971f6ce628d1b.", stop_key=""))]), rpcid=10

**Comment by manolama** [comment]
Hiya, fixed in 147b4e9046968e38e6e8b92ef3a9e08c8edd3d8f. Just download that JAR and drop it in  TSDB until we cut the next 2.3 release.
