### ISSUE TITLE
Flume : HBase Sink fails on Hortonworks sandbox

### ISSUE THREAD

**Issue by dgkris** [OpenTSDB/asynchbase#86]
I'm trying to stream some feeds onto HBase with a custom serializer. When I run flume agent I end up getting the below response :

14/06/05 21:09:33 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sandbox.hortonworks.com sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@6aa69b6c
14/06/05 21:09:33 INFO async.HBaseClient: Need to find the -ROOT- region
14/06/05 21:09:33 INFO zookeeper.ClientCnxn: Opening socket connection to server sandbox.hortonworks.com/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
14/06/05 21:09:33 INFO zookeeper.ClientCnxn: Socket connection established to sandbox.hortonworks.com/10.0.2.15:2181, initiating session
14/06/05 21:09:33 INFO zookeeper.ClientCnxn: Session establishment complete on server sandbox.hortonworks.com/10.0.2.15:2181, sessionid = 0x1466bf4ebef0020, negotiated timeout = 5000
14/06/05 21:09:33 ERROR async.HBaseClient: The znode for the -ROOT- region doesn't exist!
14/06/05 21:09:34 ERROR async.HBaseClient: The znode for the -ROOT- region doesn't exist!
14/06/05 21:09:35 ERROR async.HBaseClient: The znode for the -ROOT- region doesn't exist!
14/06/05 21:09:36 ERROR async.HBaseClient: The znode for the -ROOT- region doesn't exist!
14/06/05 21:09:37 ERROR async.HBaseClient: The znode for the -ROOT- region doesn't exist!
## flume.conf

MediaPipe.sources = Feeds MediaPipe.channels = MemChannel MediaPipe.sinks = HBASE MediaPipe.sources.Feeds.type = com.dgkris.mediapipe.FeedSource MediaPipe.sources.Feeds.channels = MemChannel MediaPipe.sources.Feeds.crawlingFrequency = 30000 MediaPipe.sinks.HBASE.channel = MemChannel MediaPipe.sinks.HBASE.type = org.apache.flume.sink.hbase.AsyncHBaseSink MediaPipe.sinks.HBASE.serializer = com.dgkris.mediapipe.FeedSerializer MediaPipe.sinks.HBASE.table = FeedTable MediaPipe.sinks.HBASE.rowKey = pubTimeRk MediaPipe.sinks.HBASE.columnFamily = FeedDetailCF MediaPipe.sinks.HBASE.serializer.columns = title,author,link,guid,description,text,html MediaPipe.sinks.HBASE.batchSize = 5000 MediaPipe.sinks.HBASE.incrementColumn = icol MediaPipe.channels.MemChannel.type = memory MediaPipe.channels.MemChannel.capacity = 10000 MediaPipe.channels.MemChannel.transactionCapacity = 100
## pom.xml

 <dependency>
            <groupId>org.hbase</groupId>
            <artifactId>asynchbase</artifactId>
            <version>1.5.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.flume</groupId>
            <artifactId>flume-ng-core</artifactId>
            <version>1.3.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.flume.flume-ng-sinks</groupId>
            <artifactId>flume-ng-hbase-sink</artifactId>
            <version>1.4.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-common</artifactId>
            <version>0.96.0-hadoop2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by IDerr** [comment]
@manolama you can close this one too
